---
- hosts: all 
  become: True 
  tasks:
    - name: test
      shell: touch /tmp/file.txt

    - name: ip address of targeted nodes
      debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
