- name: Hello World Sample
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          enabled: yes
          state: started
