
######currently this playbook is giving error on execution.
---
- name: webserver playbook
  hosts: all
  tasks:
    - name: update software
      command: "apt-get update"
    - name: install httpd
      command: "apt install httpd"
    - name: enable and start httpd
      command: "service httpd start"
    - name: creating the index.html
      copy:
        content: "welcome to awx"
        dest: /var/www/html/index.html
        node: 0444
    - name: open firewall port
      firewalld:
        service: httpd
        permanent: true
        state: enabled
        immediate: yes
      
    
